### ISSUE TITLE
Minor issue with redirection to GFG site and a typo

### ISSUE THREAD

**Issue by bhavyatyagi** [linkedin/school-of-sre#127]
1.
Inside
_school-of-sre\courses\level102\containerization_and_orchestration\intro_to_containers.md_
Line 177, clicking on the link in line _"If you want to try out a more in-depth exercise on cgroups, check out this tutorial from Geeks for Geeks."_ makes the site go Error 404 Not found. To fix this an 'https://' can be added as a prefix to the link which will fix this issue.
Page Link: https://linkedin.github.io/school-of-sre/level102/containerization_and_orchestration/intro_to_containers/

2.
Inside
_school-of-sre\courses\level102\linux_intermediate\bashscripting.md_
the monitoring script misses onto the first '#' in 
#!/bin/bash and should be **#!/bin/bash** instead of **!/bin/bash**
Page Link: https://linkedin.github.io/school-of-sre/level102/linux_intermediate/bashscripting/

Do let me know about the issues and suggested changes...

**Comment by sanketplus** [comment]
@bhavyatyagi feel free to raise a PR. thanks for reporting the issues

**Comment by bhavyatyagi** [comment]
Raised a pr as instructed. Thanks for letting me fix it :)
