### ISSUE TITLE
Katacoda.com is now closed

### ISSUE THREAD

**Issue by Samikmalhotra** [linkedin/school-of-sre#141]
Hello,
I really love how helpful this manual is and while I was going through it I found out there were some mentions of katacoda.com for hands-on labs in the kubernetes section.
Katacoda.com is now closed, actually it has become O'Reilly exclusive.
References: 
- https://www.katacoda.com/courses/kubernetes/playground
- https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html

An alternative to this can be the labs at play with kubernetes: https://labs.play-with-k8s.com/

Changes should be done primarily in the file: [orchestration_with_kubernetes.md](https://github.com/linkedin/school-of-sre/blob/main/courses/level102/containerization_and_orchestration/orchestration_with_kubernetes.md)

If approved, I would like to update this and send in a PR if allowed
Cheers!

**Comment by pylixm** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by sumeshpremraj** [comment]
@Samikmalhotra sounds good, can you open a PR?

**Comment by sumeshpremraj** [comment]
PR has been merged
