### ISSUE TITLE
word 'swimlane' in diagram

### ISSUE THREAD

**Issue by daodennis** [linkedin/school-of-sre#55]
![Image](https://linkedin.github.io/school-of-sre/systems_design/images/swimlane-1.jpg)
https://linkedin.github.io/school-of-sre/systems_design/images/swimlane-1.jpg

on this page
https://linkedin.github.io/school-of-sre/systems_design/fault-tolerance/

The word **swimlane** in the diagram is likely extraneous. Please consider revising the image. Thank you

**Comment by Diacron** [comment]
Can beginners work on this?

**Comment by vipradwivedi** [comment]
Is this really a bug or keyword `Swimlane` is intensional in both diagrams?

**Comment by sanketplus** [comment]
```
Swimlane is one of the commonly used fault isolation methodologies. Swimlane adds a barrier to the service from other services so that failure on either of them won’t affect the other. Say we roll out a new feature ‘Advertisement’ in our content sharing app. We can have two architectures
```

The swimlane block you see in both diagrams shows the isolation that the method is all about. Read closely and hopefully you will understand :)
