### ISSUE TITLE
Add observability

### ISSUE THREAD

**Issue by everton-martins** [linkedin/school-of-sre#60]
what do you think about adding an observability course?

the definition? what is a metric? how to get / store / correlate and show?
why?
Tools eg: prometheus, grafana, elk, jaeger, etc.

**Comment by sumeshpremraj** [comment]
We will discuss this within the core team and get back to you soon.

**Comment by eddie8balltoliver** [comment]
I believe that's a great idea

**Comment by everton-martins** [comment]
Hi @sumeshpremraj ,
I wrote a little article - [what-is-observability](https://medium.com/@evertonmart/what-is-observability-b3f030c5dcl)
Maybe helps,

**Comment by everton-martins** [comment]
@sumeshpremraj, how is it going?
have you discussed this with the team?

**Comment by sumeshpremraj** [comment]
We're working on an observability module, hoping to complete it by end of this month.

**Comment by kalyanceg** [comment]
@everton-martins the medium link is giving 404
We are working on a module and as @sumeshpremraj said the content should be out by end of this month
Please feel free to contribute to it if you find something missing
