### ISSUE TITLE
Contribution in Python

### ISSUE THREAD

**Issue by akrish4** [linkedin/school-of-sre#66]
I would be happy to contribute in python and html for the course section , Kindly let me know what sections or topics are left out or need to be covered ? so that I could contribute.

**Comment by eddie8balltoliver** [comment]
Help me let my mother  Faye Toliver  Overton Texas well you know I I do be up here in the comment need

**Comment by kalyanceg** [comment]
@akrish4 Thanks for your interest. We are thinking of collecting feedback from the interest groups for our next steps. We will update our ToDo in the repo shortly and if something interests you, please feel free to contribute
