### ISSUE TITLE
GNU  deserves to be included in Linux Introduction

### ISSUE THREAD

**Issue by ravish0007** [linkedin/school-of-sre#76]
Sad to see, not mentioning Linux as GNU/Linux at least at the very beginning.

Please do something about this or assign this to me.

Thank you.

Best,
Rav

**Comment by codophobia** [comment]
It makes sense to mention GNU/Linux at the beginning and describe it in brief. Will add this soon. Thanks for your suggestion.

**Comment by ravish0007** [comment]
Thank you, please close this issue once its done.

**Comment by ravish0007** [comment]
Discovered this today, it was so good
https://www.youtube.com/watch?v=UcckLr4fQQs 
I just wanted to leave a pointer for explorers

**Comment by ravish0007** [comment]
Thanks. Peace
