### ISSUE TITLE
Something i can't understand in chapter System Design -> Scalability

### ISSUE THREAD

**Issue by CuberL** [linkedin/school-of-sre#78]
> Usually, web applications can be scaled by adding resources unless there is no state stored inside the application. 

I can't understand this line at all. In my opinion, stateless systems can be scaled horizontally easier... Why the article says _unless there is no state stored inside the application_ ? 🤔

**Comment by sanketplus** [comment]
thanks @CuberL for catching this. looks like a typo. Will get it fixed :)
