### ISSUE TITLE
Suggestion to improve readability of shell commands

### ISSUE THREAD

**Issue by opethe1st** [linkedin/school-of-sre#83]
I was looking at the shell commands [here](https://linkedin.github.io/school-of-sre/git/branches/) and I found the user prompt very distracting. It currently looks like this.

```
spatel1-mn1:school-of-sre spatel1$ git branch b1
spatel1-mn1:school-of-sre spatel1$ git log --oneline --graph
* 7f3b00e (HEAD -> master, b1) adding file 2
* df2fb7a adding file 1
```
but it would be better in my opinion if it looked like this 

```
$ git branch b1
$ git log --oneline --graph
* 7f3b00e (HEAD -> master, b1) adding file 2
* df2fb7a adding file 1
```
or since the current branch important to understand what a git command would do.

```
(master)$ git branch b1
(master)$ git log --oneline --graph
* 7f3b00e (HEAD -> master, b1) adding file 2
* df2fb7a adding file 1
```

I think this is better and easier to understand since the git commands stand out

What do you think?

I'm also willing to make a PR for this if this sounds like a reasonable idea.

Thanks for sharing free knowledge, I wish I came across this when I was in uni.
Cheers!

**Comment by kalyanceg** [comment]
We will be happy to review the PR @opethe1st 
@sanketplus please leave your thoughts as you own the Git module
Based on the outcome we can decide if we have to update Guidelines for future bash snippets

**Comment by sanketplus** [comment]
totally valid suggestion @opethe1st. Do raise a PR. Latter suggestion looks good but since the branch would not be shown unless you customize bash prompt, let's go with the first suggestion.

Happy to know this was useful :)

**Comment by opethe1st** [comment]
I am fine with customising the bash prompt :) but the first is also fine. At work right now, so this will be later after work. Cheers

**Comment by sanketplus** [comment]
appreciate your help @opethe1st, PR merged 🎉

**Comment by opethe1st** [comment]
glad to help! Cheers!
