### ISSUE TITLE
Code snippet images are very small

### ISSUE THREAD

**Issue by abdelrahmanahmed** [linkedin/school-of-sre#98]
It would be better to add a better image quality for the code snippets, or add interactive shell.
![image](https://user-images.githubusercontent.com/8146379/113489623-896ca900-94c5-11eb-94e8-ab69269e478b.png)
![image](https://user-images.githubusercontent.com/8146379/113489671-d81a4300-94c5-11eb-8442-1aa23d18ffb6.png)

**Comment by kalyanceg** [comment]
Thanks for your suggestion @abdelrahmanahmed 

We will keep you posted as we work on this

**Comment by Zaidtech** [comment]
Can I work on this issue? @kalyanceg

**Comment by poudyalamit** [comment]
Is this issue open now?

**Comment by sumeshpremraj** [comment]
Yes, this issue is still open, feel free to pick it up @poudyalamit

**Comment by poudyalamit** [comment]
Surely I will be going to solve this issue.

**Comment by poudyalamit** [comment]
@sumeshpremraj should I add same kind of terminal image as used in the file?

**Comment by poudyalamit** [comment]
I have resolved this issue with pull request #153

**Comment by poudyalamit** [comment]
I have resolved the issue with pull request #154

**Comment by poudyalamit** [comment]
@sumeshpremraj You may review and give feedback to pull request #154

**Comment by stormic-nomad-nishant** [comment]
PR merged
